### PR TITLE
Task 5

### PR DESCRIPTION
**Pull request by ilya-moskovtsev**
Original Task: https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task5-import-to-s3/task.md

Evaluation criteria
Reviewers should verify the lambda functions by invoking them through provided URLs.
1 - File serverless.yml contains configuration for importProductsFile function
3 - The importProductsFile lambda function returns a correct response which can be used to upload a file into the S3 bucket
   https://peub31gawe.execute-api.us-east-1.amazonaws.com/dev/import?name=fileName
4 - Frontend application is integrated with importProductsFile lambda
   https://dyzw59fxpwli2.cloudfront.net/admin/products
5 - The importFileParser lambda function is implemented and serverless.yml contains configuration for the lambda
Additional (optional) tasks
+1 - async/await is used in lambda functions
+1 - importProductsFile lambda is covered by unit tests (aws-sdk-mock can be used to mock S3 methods - https://www.npmjs.com/package/aws-sdk-mock)
+1 - At the end of the stream the lambda function should move the file from the uploaded folder into the parsed folder (move the file means that file should be copied into parsed folder, and then deleted from uploaded folder)

Front-end pull request: https://github.com/ilya-moskovtsev/nodejs-aws-fe/pull/5
CloudFront: https://dyzw59fxpwli2.cloudfront.net/

### CODE REVIEW

**Comment by AmsterGet** [comment]
Are the files downloading correctly? I am getting 403 error.

**Review by AmsterGet — COMMENTED** [review]
Are the files uploading correctly? I am getting 403 error.

**Comment by AmsterGet** [comment]
@ilya-moskovtsev

**Comment by ilya-moskovtsev** [comment]
> Are the files uploading correctly? I am getting 403 error.

I allow files to be uploaded only from CloudFront. Here is my S3 CORS:
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "https://dyzw59fxpwli2.cloudfront.net"
        ],
        "ExposeHeaders": []
    },
    {
        "AllowedHeaders": [],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```

**Pull request merged**
